import { type ReactNode } from "react";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

import { Providers } from "./providers";

import Layout from "@/src/widgets/layout";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface Props {
  children: ReactNode;
  modal: ReactNode;
}
export default function RootLayout(props: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Layout>
            {props.children}
            {props.modal}
          </Layout>
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
