import type { Metadata } from 'next'
import { ReactNode } from 'react'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'
import { Toaster } from 'react-hot-toast'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
interface Props {
    children: ReactNode
    modal: ReactNode
}
export default function RootLayout(props:Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Providers>
          {props.children}
          {props.modal}
      </Providers>
      <Toaster />
      </body>
    </html>
  )
}
